import { Chat, Message, Story } from '../types';

export function generateMockChats(): Chat[] {
  const now = Date.now();

  return [
    {
      id: 'chat-1',
      type: 'personal',
      name: 'Alice Johnson',
      participants: ['current-user', 'user-1'],
      unreadCount: 3,
      isPinned: true,
      isFavourite: true,
      isArchived: false,
      lastMessage: {
        id: 'msg-1',
        chatId: 'chat-1',
        senderId: 'user-1',
        content: 'Hey! How are you doing?',
        timestamp: now - 120000,
        type: 'text',
        status: 'delivered',
      },
    },
    {
      id: 'chat-2',
      type: 'group',
      name: 'Family Group',
      participants: ['current-user', 'user-2', 'user-3', 'user-4'],
      unreadCount: 0,
      isPinned: true,
      isFavourite: false,
      isArchived: false,
      memberCount: 4,
      description: 'Family chat for updates and planning',
      lastMessage: {
        id: 'msg-2',
        chatId: 'chat-2',
        senderId: 'user-2',
        content: 'Dinner at 7 PM tonight?',
        timestamp: now - 1800000,
        type: 'text',
        status: 'read',
      },
    },
    {
      id: 'chat-3',
      type: 'personal',
      name: 'Bob Smith',
      participants: ['current-user', 'user-3'],
      unreadCount: 0,
      isPinned: false,
      isFavourite: false,
      isArchived: false,
      lastMessage: {
        id: 'msg-3',
        chatId: 'chat-3',
        senderId: 'current-user',
        content: 'Sounds good! See you then.',
        timestamp: now - 3600000,
        type: 'text',
        status: 'read',
      },
    },
    {
      id: 'chat-4',
      type: 'channel',
      name: 'Tech News Daily',
      participants: ['current-user'],
      unreadCount: 12,
      isPinned: false,
      isFavourite: true,
      isArchived: false,
      memberCount: 25432,
      description: 'Latest tech news and updates',
      lastMessage: {
        id: 'msg-4',
        chatId: 'chat-4',
        senderId: 'channel-admin',
        content: 'Breaking: New AI breakthrough announced!',
        timestamp: now - 7200000,
        type: 'text',
        status: 'delivered',
      },
    },
    {
      id: 'chat-5',
      type: 'group',
      name: 'Work Team',
      participants: ['current-user', 'user-5', 'user-6', 'user-7', 'user-8'],
      unreadCount: 5,
      isPinned: false,
      isFavourite: false,
      isArchived: false,
      memberCount: 5,
      description: 'Project collaboration',
      lastMessage: {
        id: 'msg-5',
        chatId: 'chat-5',
        senderId: 'user-5',
        content: 'Meeting in 10 minutes!',
        timestamp: now - 600000,
        type: 'text',
        status: 'delivered',
      },
    },
    {
      id: 'chat-6',
      type: 'personal',
      name: 'Emma Wilson',
      participants: ['current-user', 'user-6'],
      unreadCount: 0,
      isPinned: false,
      isFavourite: false,
      isArchived: false,
      lastMessage: {
        id: 'msg-6',
        chatId: 'chat-6',
        senderId: 'user-6',
        content: 'Thanks for your help!',
        timestamp: now - 86400000,
        type: 'text',
        status: 'read',
      },
    },
    {
      id: 'chat-7',
      type: 'group',
      name: 'Weekend Warriors',
      participants: ['current-user', 'user-7', 'user-8', 'user-9'],
      unreadCount: 0,
      isPinned: false,
      isFavourite: false,
      isArchived: false,
      memberCount: 4,
      description: 'Weekend plans and adventures',
      lastMessage: {
        id: 'msg-7',
        chatId: 'chat-7',
        senderId: 'user-7',
        content: 'Anyone up for hiking this Saturday?',
        timestamp: now - 172800000,
        type: 'text',
        status: 'read',
      },
    },
    {
      id: 'chat-8',
      type: 'personal',
      name: 'David Lee',
      participants: ['current-user', 'user-8'],
      unreadCount: 1,
      isPinned: false,
      isFavourite: false,
      isArchived: false,
      lastMessage: {
        id: 'msg-8',
        chatId: 'chat-8',
        senderId: 'user-8',
        content: 'Can you send me that document?',
        timestamp: now - 300000,
        type: 'text',
        status: 'delivered',
      },
    },
    {
      id: 'chat-9',
      type: 'channel',
      name: 'Daily Motivation',
      participants: ['current-user'],
      unreadCount: 3,
      isPinned: false,
      isFavourite: false,
      isArchived: false,
      memberCount: 89234,
      description: 'Daily motivational quotes and stories',
      lastMessage: {
        id: 'msg-9',
        chatId: 'chat-9',
        senderId: 'channel-admin',
        content: '"The only way to do great work is to love what you do." - Steve Jobs',
        timestamp: now - 43200000,
        type: 'text',
        status: 'delivered',
      },
    },
    {
      id: 'chat-10',
      type: 'personal',
      name: 'Sarah Chen',
      participants: ['current-user', 'user-9'],
      unreadCount: 0,
      isPinned: false,
      isFavourite: false,
      isArchived: false,
      lastMessage: {
        id: 'msg-10',
        chatId: 'chat-10',
        senderId: 'current-user',
        content: 'Let me know when you are free!',
        timestamp: now - 259200000,
        type: 'text',
        status: 'read',
      },
    },
  ];
}

export function generateMockMessages(): Record<string, Message[]> {
  const now = Date.now();

  return {
    'chat-1': [
      {
        id: 'msg-1-1',
        chatId: 'chat-1',
        senderId: 'current-user',
        content: 'Hi Alice! How have you been?',
        timestamp: now - 7200000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-1-2',
        chatId: 'chat-1',
        senderId: 'user-1',
        content: 'Hi! I have been great, thanks for asking!',
        timestamp: now - 7140000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-1-3',
        chatId: 'chat-1',
        senderId: 'user-1',
        content: 'Working on some exciting projects lately.',
        timestamp: now - 7100000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-1-4',
        chatId: 'chat-1',
        senderId: 'current-user',
        content: 'That sounds amazing! Tell me more about it.',
        timestamp: now - 3600000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-1-5',
        chatId: 'chat-1',
        senderId: 'user-1',
        content: 'Hey! How are you doing?',
        timestamp: now - 120000,
        type: 'text',
        status: 'delivered',
      },
    ],
    'chat-2': [
      {
        id: 'msg-2-1',
        chatId: 'chat-2',
        senderId: 'user-2',
        content: 'Good morning everyone!',
        timestamp: now - 21600000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-2-2',
        chatId: 'chat-2',
        senderId: 'user-3',
        content: 'Morning! Hope everyone has a great day.',
        timestamp: now - 21000000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-2-3',
        chatId: 'chat-2',
        senderId: 'current-user',
        content: 'Good morning! 👋',
        timestamp: now - 18000000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-2-4',
        chatId: 'chat-2',
        senderId: 'user-2',
        content: 'Dinner at 7 PM tonight?',
        timestamp: now - 1800000,
        type: 'text',
        status: 'read',
      },
    ],
    'chat-3': [
      {
        id: 'msg-3-1',
        chatId: 'chat-3',
        senderId: 'user-3',
        content: 'Want to grab coffee tomorrow?',
        timestamp: now - 86400000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-3-2',
        chatId: 'chat-3',
        senderId: 'current-user',
        content: 'Sure! What time works for you?',
        timestamp: now - 82800000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-3-3',
        chatId: 'chat-3',
        senderId: 'user-3',
        content: 'How about 10 AM?',
        timestamp: now - 79200000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-3-4',
        chatId: 'chat-3',
        senderId: 'current-user',
        content: 'Sounds good! See you then.',
        timestamp: now - 3600000,
        type: 'text',
        status: 'read',
      },
    ],
    'chat-5': [
      {
        id: 'msg-5-1',
        chatId: 'chat-5',
        senderId: 'user-5',
        content: 'Team, we need to discuss the Q4 roadmap.',
        timestamp: now - 7200000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-5-2',
        chatId: 'chat-5',
        senderId: 'user-6',
        content: 'I can present the design updates.',
        timestamp: now - 7000000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-5-3',
        chatId: 'chat-5',
        senderId: 'current-user',
        content: 'I will cover the technical implementation.',
        timestamp: now - 6800000,
        type: 'text',
        status: 'read',
      },
      {
        id: 'msg-5-4',
        chatId: 'chat-5',
        senderId: 'user-5',
        content: 'Meeting in 10 minutes!',
        timestamp: now - 600000,
        type: 'text',
        status: 'delivered',
      },
    ],
  };
}

export function generateMockStories(): Record<string, Story[]> {
  const now = Date.now();

  return {
    'user-1': [
      {
        id: 'story-1',
        userId: 'user-1',
        content: 'Beautiful sunset today! 🌅',
        type: 'text',
        backgroundColor: '#FF6B6B',
        timestamp: now - 3600000,
        views: ['current-user'],
      },
    ],
    'user-2': [
      {
        id: 'story-2',
        userId: 'user-2',
        content: 'Coffee time ☕',
        type: 'text',
        backgroundColor: '#4ECDC4',
        timestamp: now - 7200000,
        views: [],
      },
    ],
    'user-3': [
      {
        id: 'story-3',
        userId: 'user-3',
        content: 'New adventure begins!',
        type: 'text',
        backgroundColor: '#95E1D3',
        timestamp: now - 10800000,
        views: ['current-user'],
      },
    ],
    'user-6': [
      {
        id: 'story-4',
        userId: 'user-6',
        content: 'Celebrating small wins! 🎉',
        type: 'text',
        backgroundColor: '#F38181',
        timestamp: now - 14400000,
        views: [],
      },
    ],
  };
}
